#! /bin/sh

xrandr --output LVDS1 --auto --primary
xrandr --output VGA1 --auto --left-of LVDS1


sxhkd &
$HOME/.config/polybar/launch.sh &
nm-applet &
feh --bg-scale /home/holzel/Bilder/Wal3.png
compton --config /home/holzel/.config/compton.conf &
setxkbmap -option compose:ralt


bspc monitor VGA1 -d I II III IV V 
bspc monitor LVDS1 -d VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Die Farbe das Fenster
bspc config focused_border_color \#3FC997
bspc config normal_border_color \#0F0C14

#Die Farbe eines neues Fenster
bspc config presel_feedback_color \#3FC997

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
